config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'homes/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'homes#index'
  get 'hearts/toggle_heart/:id' => 'hearts#toggle_heart', as: :hearts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart.rb
class Heart < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :hearts
    has_many :users, through: :hearts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :hearts
  has_many :posts, through: :hearts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
    def toggle_heart
        heart = Heart.find_by(user_id: current_user.id, post_id: params[:id])
        
        if heart.nil?
            Heart.create(user_id: current_user.id, post_id: params[:id])
        else
            heart.destroy
        end
        
        redirect_to request.referrer
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

<% if user_signed_in? %>
<p>현재 로그인된 유저의 이메일 : <%= current_user.email %></p>
<p><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></p>
<% else %>
<p><%= link_to "로그인", new_user_session_path %></p>
<% end %>

<hr>
<p><%= link_to "게시글작성하기", posts_path %></p>
<hr>
<% @posts.each do |p| %>
    [게시글 제목] <%= p.title %>
    <%= link_to "좋아요! #{p.hearts.size}", hearts_path(p.id) %>
    &nbsp; 
    <% p.hearts.each do |h| %>
        | <%= @users.find(h.user_id).email %>
    <% end %>
    <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Like</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/destroy.js.erb
$('#del_<%= @post.id %>').remove();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr id='del_<%= post.id %>'>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to '상세보기', post %></td>
        <td><%= link_to '수정하기', edit_post_path(post) %></td>
        <td><%= link_to '삭제하기', post, method: :delete, data: { confirm: '정말로 삭제하시겠습니까?'}, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '새글작성하기', new_post_path %> <%= link_to '홈 화면으로', homes_index_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>